name = "RecurrenceMicrostatesAnalysis"
uuid = "cb83a08b-85c6-4e94-91aa-4e946c7d4f0c"
version = "0.4.0-dev"
repo = "https://github.com/DynamicsUFPR/RecurrenceMicrostatesAnalysis.jl"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
ComplexityMeasures = "ab4b797d-85ee-42ba-b621-05d793b346a2"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StateSpaceSets = "40b095a5-5852-4c12-98c7-d43bf788e795"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Adapt = "4.4.0"
Atomix = "1.1.2"
ComplexityMeasures = "3.8.5"
Distances = "0.10.12"
GPUArraysCore = "0.2.0"
KernelAbstractions = "0.9.39"
Random = "1.10.9"
Random123 = "1.7.1"
Reexport = "1.2.2"
StateSpaceSets = "2.5.3"
StaticArrays = "1.9.15"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
RecurrenceAnalysis = "639c3291-70d9-5ea2-8c5b-839eba1ee399"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "RecurrenceAnalysis", "Distributions"]
